apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: tit1esi92-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.325cb0b3-86b0-47f8-8c0c-ff0f4f8f85ac.prod.konfluxeaas.com/rhtap/rhtap-qe-dotnet-basic:537fa2c843033816b0fc687429a919f9d9673b8e@sha256:a0ff38598b4a010c18abc3da72a386ed99e4f9eff23558f578ab6b6099c0737f
          name: container-image
